version: "3.4"

services:
  miner:
    build:
      context: ../../
    image: "vocdoni/dvotenode"
    volumes:
      - "run:/app/run"
    ports:
      - "26656:26656"
      - "26657:26657"
    environment:
      DVOTE_MODE: miner
    logging:
      driver: json-file
      options:
        max-size: "20m"
        max-file: "10"

volumes:
  run: {}
