version: "3.4"
services:
  eth:
    image: parity/parity:v2.7.2-stable
    ports:
      - "9080:9080"
      - "37671:37671"
      - "9081:9081"
    restart: ${RESTART:-no}
    env_file: env
    user: root
    volumes:
      - "eth:/app/eth"
      - ./files:/app/files
    entrypoint: /app/files/parity.sh $RESTART

volumes:
  eth: {}
