version: "3.4"

services:
  oracle:
    build:
      context: ../../
    image: "vocdoni/dvotenode"
    volumes:
      - "run:/app/run"
    ports:
      - "9091:9091"
      - "9092:9092"
      - "30303:30303"
      - "30303:30303/udp"
      - "26656:26656"
      - "26657:26657"
    env_file:
      - ./env
    environment:
      mode: oracle
      #EXTRA_OPTS: "$EXTRA_OPTS --volume-driver memfs"
    logging:
      driver: json-file
      options:
        max-size: "20m"
        max-file: "10"

volumes:
  run: {}
