version: "3.7"

services:
  seed:
    image: "dvotenode"
    build:
      context: ../../
    env_file: "${COMPOSE_HOST_PATH:-.}/env.seed"
    volumes:
      - data-seed:/app/run/
      - ${COMPOSE_HOST_PATH:-.}/genesis.json:/app/misc/genesis.json
    networks:
      localnet:
        ipv4_address: 10.17.14.15
    ports:
      - "26680-26681:26656-26657"

  miner0:
    image: "dvotenode"
    build:
      context: ../../
    env_file: "${COMPOSE_HOST_PATH:-.}/env.miner0"
    volumes:
      - data-miner0:/app/run/
      - ${COMPOSE_HOST_PATH:-.}/genesis.json:/app/misc/genesis.json
    networks:
      localnet:
        ipv4_address: 10.17.14.2
    ports:
      - "26673-26674:26656-26657"

  miner1:
    image: "dvotenode"
    build:
      context: ../../
    env_file: "${COMPOSE_HOST_PATH:-.}/env.miner1"
    volumes:
      - data-miner1:/app/run/
      - ${COMPOSE_HOST_PATH:-.}/genesis.json:/app/misc/genesis.json
    networks:
      localnet:
        ipv4_address: 10.17.14.3
    ports:
      - "26658-26659:26656-26657"

  miner2:
    image: "dvotenode"
    build:
      context: ../../
    env_file: "${COMPOSE_HOST_PATH:-.}/env.miner2"
    volumes:
      - data-miner2:/app/run/
      - ${COMPOSE_HOST_PATH:-.}/genesis.json:/app/misc/genesis.json
    networks:
      localnet:
        ipv4_address: 10.17.14.4
    ports:
      - "26660-26661:26656-26657"

  miner3:
    image: "dvotenode"
    build:
      context: ../../
    env_file: "${COMPOSE_HOST_PATH:-.}/env.miner3"
    volumes:
      - data-miner3:/app/run/
      - ${COMPOSE_HOST_PATH:-.}/genesis.json:/app/misc/genesis.json
    networks:
      localnet:
        ipv4_address: 10.17.14.7
    ports:
      - "26670-26671:26656-26657"

  oracle:
    image: "dvotenode"
    build:
      context: ../../
    env_file: "${COMPOSE_HOST_PATH:-.}/env.oracle"
    volumes:
      - data-oracle:/app/run/
      - ${COMPOSE_HOST_PATH:-.}/genesis.json:/app/misc/genesis.json
    networks:
      localnet:
        ipv4_address: 10.17.14.5
    ports:
      - "30304:30303"
      - "32001:32000"
      - "26662-26663:26656-26657"

  gateway:
    image: "dvotenode"
    build:
      context: ../../
    env_file: "${COMPOSE_HOST_PATH:-.}/env.gateway"
    volumes:
      - data-gateway:/app/run/
      - ${COMPOSE_HOST_PATH:-.}/genesis.json:/app/misc/genesis.json
    networks:
      localnet:
        ipv4_address: 10.17.14.6
    ports:
      - "30303:30303"
      - "32000:32000"
      - "9090-9092:9090-9092"
      - "26664-26665:26656-26657"

  test:
    image: "dvotenode-test"
    build:
      context: ../../
      target: test
    networks:
      localnet:
        ipv4_address: 10.17.14.100
    command: "true"

networks:
  localnet:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.17.14.0/24

volumes:
  data-seed: {}
  data-miner0: {}
  data-miner1: {}
  data-miner2: {}
  data-miner3: {}
  data-oracle: {}
  data-gateway: {}
