stages:
  - build
  - test
  - release

variables:
  # DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2
  DVOTE_GATEWAY_BUILD_IMAGE: ${CI_REGISTRY_IMAGE}/vocdoni-gateway:${CI_COMMIT_REF_SLUG}
  DVOTE_GATEWAY_RELEASE_IMAGE: ${CI_REGISTRY_IMAGE}/vocdoni-gateway:latest

  GOPATH:  ${CI_PROJECT_DIR}/.cache/gopath  # to cache Go module downloads
  GOCACHE: ${CI_PROJECT_DIR}/.cache/gocache # to cache Go build archives
  GOFLAGS: -mod=readonly

cache:
  key: always-same-cache
  paths:
    - .cache/

go-test:
  image: golang:1.13.5
  stage: test
  script:
    - go env
    - go test ./...

docker-release:
  image: docker:stable
  services:
    - docker:dind
  stage: release
  script:
    - docker build --pull -t ${DVOTE_GATEWAY_BUILD_IMAGE} -f dockerfile.gateway .
    - docker tag ${DVOTE_GATEWAY_BUILD_IMAGE} ${DVOTE_GATEWAY_RELEASE_IMAGE}
    - docker login -u gitlab-ci-token -p ${CI_BUILD_TOKEN} ${CI_REGISTRY}
    - docker push ${DVOTE_GATEWAY_BUILD_IMAGE}
    - docker push ${DVOTE_GATEWAY_RELEASE_IMAGE}
  only:
    - master
