issues:
        max-same-issues: 0
        exclude-use-default: false
linters:
        enable:
        - gosec
        - misspell
        - gomnd
        - gofumpt
        - lll
linters-settings:
        lll:
                line-length: 100
