version: "3"

services:

  miner0:
    container_name: miner0
    image: "vocdoni/miner"
    entrypoint: "dockerfiles/miner/files/minerStart.sh"
    command: ""
    env_file: "dockerfiles/testsuite/env.miner0"
    volumes:
      - $PWD/run/miner0:/root/.dvote/
    networks:
      localnet:
        ipv4_address: 10.17.14.2
    ports: 
      - "26656-26657:26656-26657"    

  miner1:
    container_name: miner1
    image: "vocdoni/miner"
    entrypoint: "dockerfiles/miner/files/minerStart.sh"
    env_file: "dockerfiles/testsuite/env.miner1"
    volumes:
      - $PWD/run/miner1:/root/.dvote/
    networks:
      localnet:
        ipv4_address: 10.17.14.3
    ports: 
      - "26658-26659:26656-26657"    

  miner2:
    container_name: miner2
    image: "vocdoni/miner"
    entrypoint: "dockerfiles/miner/files/minerStart.sh"
    env_file: "dockerfiles/testsuite/env.miner2"
    volumes:
      - $PWD/run/miner2:/root/.dvote/
    networks:
      localnet:
        ipv4_address: 10.17.14.4
    ports: 
      - "26660-26661:26656-26657"

  gateway:
    container_name: gateway
    image: "vocdoni/gateway"
    entrypoint: "dockerfiles/gateway/files/gatewayStart.sh"
    env_file: "dockerfiles/testsuite/env.gateway"
    volumes:
      - $PWD/run/gateway:/root/.dvote/
    networks:
      localnet:
        ipv4_address: 10.17.14.6
    ports: 
      - "30303:30303"
      - "32000:32000"
      - "9090-9092:9090-9092"
      - "26664-26665:26656-26657"

networks:
  localnet:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.17.14.0/24
